parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - ./packages/*/tsconfig.json
plugins:
  - deprecation
  - simple-import-sort
  - header
extends:
  - standard-with-typescript
  - prettier
rules:
  'deprecation/deprecation': 'warn'
  'simple-import-sort/imports': 'error'
  'simple-import-sort/exports': 'error'
  'header/header': [2, 'etc/eslint/header.js']
  # Disabled due to a false positive: https://github.com/typescript-eslint/typescript-eslint/issues/4689
  '@typescript-eslint/restrict-plus-operands': ['off']
  '@typescript-eslint/restrict-template-expressions': ['off']
ignorePatterns:
  - 'coverage/*'
  - 'lib/*'
  - 'etc/*'
  - '*.js'
